import CompensationEntity from "./compensation.entity"
import PaymentEntity from "./payment.entity"
import TotalWithTaxEntity from "./totalWithTax.entity"

export class InvoiceInfoEntity {
    constructor(
        public id: number,
        public uuid: string,
        public issueDate: Date,
        public establishmentAddress: string,
        public specialTaxpayer: string,
        public accountingObligation: string,
        public foreignTrade: string,
        public incoTermInvoice: string,
        public incoTermLocation: string,
        public countryOfOrigin: string,
        public portOfShipment: string,
        public portOfDestination: string,
        public destinationCountry: string,
        public acquisitionCountry: string,
        public buyerIdentificationType: string,
        public deliveryNote: string,
        public buyerBusinessName: string,
        public buyerIdentification: string,
        public buyerAddress: string,
        public totalWithoutTaxes: number,
        public totalSubsidy: number,
        public incoTermTotalWithoutTaxes: string,
        public totalDiscount: number,
        public reimbursementDocCode: number,
        public totalReimbursementInvoices: number,
        public totalReimbursementTaxableBase: number,
        public totalReimbursementTax: number,
        public tip: number,
        public internationalFreight: number,
        public internationalInsurance: number,
        public customsExpenses: number,
        public otherTransportExpenses: number,
        public totalAmount: number,
        public currency: string,
        public plate: string,
        public vatWithheldValue: number,
        public incomeTaxWithheldValue: number,
        public totalWithTaxes: TotalWithTaxEntity[],
        public totalTaxesCodeCero: string,
        public totalTaxesCodeTwo: string,
        public totalTaxesCodeThree: string,
        public totalTaxesCodeFour: string,
        public totalTaxesCodeFive: string,
        public totalTaxesCodeSix: string,
        public totalTaxesCodeSeven: string,
        public totalTaxesCodeEight: string,
        public totalTaxesCodeTen: string,
        public totalIce: string,
        public totalIrbpnr: string,
        public compensations: CompensationEntity[],
        public payments: PaymentEntity[],
        public invoiceId: number,
        public createdAt: Date,
        public updatedAt: Date,
        public deletedAt: Date | null
    ){}

    static create(object:{[key:string]:any}): InvoiceInfoEntity {
        const { 
            id, 
            uuid, 
            issueDate, 
            establishmentAddress,
            specialTaxpayer,
            accountingObligation,
            foreignTrade,
            incoTermInvoice,
            incoTermLocation,
            countryOfOrigin,
            portOfShipment,
            portOfDestination,
            destinationCountry,
            acquisitionCountry,
            buyerIdentificationType,
            deliveryNote,
            buyerBusinessName,
            buyerIdentification,
            buyerAddress,
            totalWithoutTaxes,
            totalSubsidy,
            incoTermTotalWithoutTaxes,
            totalDiscount,
            reimbursementDocCode,
            totalReimbursementInvoices,
            totalReimbursementTaxableBase,
            totalReimbursementTax,
            tip,
            internationalFreight,
            internationalInsurance,
            customsExpenses,
            otherTransportExpenses,
            totalAmount,
            currency,
            plate,
            vatWithheldValue,
            incomeTaxWithheldValue,
            totalWithTaxes,
            totalTaxesCodeCero,
            totalTaxesCodeTwo,
            totalTaxesCodeThree,
            totalTaxesCodeFour,
            totalTaxesCodeFive,
            totalTaxesCodeSix,
            totalTaxesCodeSeven,
            totalTaxesCodeEight,
            totalTaxesCodeTen,
            totalIce,
            totalIrbpnr,
            compensations, 
            payments,
            invoiceId, 
            createdAt, updatedAt, deletedAt } = object

        return new InvoiceInfoEntity(
            id,
            uuid,
            issueDate,
            establishmentAddress,
            specialTaxpayer,
            accountingObligation,
            foreignTrade,
            incoTermInvoice,
            incoTermLocation,
            countryOfOrigin,
            portOfShipment,
            portOfDestination,
            destinationCountry,
            acquisitionCountry,
            buyerIdentificationType,
            deliveryNote,
            buyerBusinessName,
            buyerIdentification,
            buyerAddress,
            totalWithoutTaxes,
            totalSubsidy,
            incoTermTotalWithoutTaxes,
            totalDiscount,
            reimbursementDocCode,
            totalReimbursementInvoices,
            totalReimbursementTaxableBase,
            totalReimbursementTax,
            tip,
            internationalFreight,
            internationalInsurance,
            customsExpenses,
            otherTransportExpenses,
            totalAmount,
            currency,
            plate,
            vatWithheldValue,
            incomeTaxWithheldValue,
            totalWithTaxes,
            parseFloat(totalTaxesCodeCero).toPrecision(4),
            parseFloat(totalTaxesCodeTwo).toPrecision(4),
            parseFloat(totalTaxesCodeThree).toPrecision(4),
            parseFloat(totalTaxesCodeFour).toPrecision(4),
            parseFloat(totalTaxesCodeFive).toPrecision(4),
            parseFloat(totalTaxesCodeSix).toPrecision(4),
            parseFloat(totalTaxesCodeSeven).toPrecision(4),
            parseFloat(totalTaxesCodeEight).toPrecision(4),
            parseFloat(totalTaxesCodeTen).toPrecision(4),
            parseFloat(totalIce).toPrecision(4),
            parseFloat(totalIrbpnr).toPrecision(4),
            compensations,
            payments,
            invoiceId,
            createdAt,
            updatedAt,
            deletedAt ? deletedAt : null
        )
    }
}